---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# LRDemo

<!-- badges: start -->
<!-- badges: end -->

The goal of LRDemo is to implement a binary or multinomial logistic regression via gradient descent. Helper functions are carried out in C++/ Rcpp for optimized computation. 

## Installation

You can install the development version of LRDemo like so:

``` r
# install.packages("devtools")
devtools::install_github("YOUR_GITHUB_USERNAME/LRDemo")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(LRDemo)

set.seed(1234567)
x <- matrix(rnorm(200), ncol = 2)
p <- 1 / (1 + exp(-(x[, 1] - x[, 2])))
y <- rbinom(nrow(x), size = 1, prob = p)

fit  <- logRegModel(x, y, family = "binomial", nIter = 500)
phat <- predict(fit, x, type = "response")
mean((phat > 0.5) == y)

```
