// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fooCpp
NumericVector fooCpp(NumericVector x);
RcppExport SEXP _LRDemo_fooCpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fooCpp(x));
    return rcpp_result_gen;
END_RCPP
}
// logRegBinGradCpp
List logRegBinGradCpp(const NumericMatrix X, const NumericVector y, const NumericVector beta);
RcppExport SEXP _LRDemo_logRegBinGradCpp(SEXP XSEXP, SEXP ySEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(logRegBinGradCpp(X, y, beta));
    return rcpp_result_gen;
END_RCPP
}
// logRegOvrCpp
List logRegOvrCpp(const NumericMatrix X, const IntegerVector y, const NumericMatrix betaMat);
RcppExport SEXP _LRDemo_logRegOvrCpp(SEXP XSEXP, SEXP ySEXP, SEXP betaMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type betaMat(betaMatSEXP);
    rcpp_result_gen = Rcpp::wrap(logRegOvrCpp(X, y, betaMat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LRDemo_fooCpp", (DL_FUNC) &_LRDemo_fooCpp, 1},
    {"_LRDemo_logRegBinGradCpp", (DL_FUNC) &_LRDemo_logRegBinGradCpp, 3},
    {"_LRDemo_logRegOvrCpp", (DL_FUNC) &_LRDemo_logRegOvrCpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_LRDemo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
