# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fooCpp <- function(x) {
    .Call(`_LRDemo_fooCpp`, x)
}

logRegBinGradCpp <- function(X, y, beta) {
    .Call(`_LRDemo_logRegBinGradCpp`, X, y, beta)
}

logRegOvrCpp <- function(X, y, betaMat) {
    .Call(`_LRDemo_logRegOvrCpp`, X, y, betaMat)
}

